SurveyCreator/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :surveys do 
    resources :results, only: [:index, :new, :create, :show]
    collection do
        get 'published'
    end
    
  end 

  get 'pages/home'

  get 'pages/contact'

  get 'pages/about'

   root 'pages#home'

end

SurveyCreator/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :response
end

SurveyCreator/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers
  validates_presence_of :question_content
end

SurveyCreator/app/models/result.rb
class Result < ActiveRecord::Base
	belongs_to :survey
	has_many :answers

	accepts_nested_attributes_for :answers
end

SurveyCreator/app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :results

  validates_presence_of :name
  accepts_nested_attributes_for :questions
end

SurveyCreator/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :surveys, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

SurveyCreator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SurveyCreator/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

SurveyCreator/app/controllers/results_controller.rb
class ResultsController < ApplicationController
	before_action :set_result, only: [:show]

  # GET /results
  # GET /results.json
  def index
    @survey = Survey.find(params[:survey_id])
    @results = @survey.results.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  	@survey = Survey.find(params[:survey_id])
  	@result = @survey.results.find(params[:id])
  end

  # GET /results/new
  def new
    @survey = Survey.find(params[:survey_id])
    @result = @survey.results.build
    @survey.questions.size.times{@result.answers.build}
  end

  # POST /results
  # POST /results.json

  def statistics
    @survey = Survey.find(params[:survey_id])
    @result = @survey.results.find(params[:id])
  end
  def create
    @survey = Survey.find(params[:survey_id])
    @result = @survey.results.build(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to [@result.survey,@result], notice: 'Question was successfully created.' }
        format.json { render :index, status: :created, location: [@result.survey,@result] }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:survey_id, 
      	answers_attributes: [:id,:result_id, :question_id, :answer_content])
    end
end

SurveyCreator/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

	def index
		@surveys = Survey.all
	end

	def published 
		@surveys = Survey.where(:status => true).order("name DESC")
	end 

	def new
		@survey = Survey.new
		5.times{@survey.questions.build}
	end

	def show
		@survey = Survey.find(params[:id])
	end 

	def edit
		@survey = Survey.find(params[:id])
	end

	def create
	    @survey = current_user.surveys.new(survey_params)
		respond_to do |format|
			if @survey.save
				format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
			else
				format.html { render :new }
			end
		end
	end

	def update
		@survey = Survey.find(params[:id])
	    respond_to do |format|
			if @survey.update(survey_params)
				format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		@survey = Survey.find(params[:id]) 
		@survey.destroy
		respond_to do |format|
			format.html{redirect_to surveys_url, notice: "Survey was successfully destroyed"}
		end 
	end 


	private 

	def set_survey
      	@survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
     def survey_params
      	params.require(:survey).permit(:name, :status, :user_id, 
      		questions_attributes:[:id, :question_content, :survey_id])
    end
end

SurveyCreator/app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_remove_fields(name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  	end
  	def link_to_add_fields(name, f, association)
  		new_object = f.object.class.reflect_on_association(association).klass.new
    	fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      	render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
  module ApplicationHelper
  def page_title
    "Survey Creator"
  end
end
end

SurveyCreator/app/helpers/devise_test_helper.rb
module DeviseTestHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

SurveyCreator/app/helpers/link_to_function_helper.rb
module LinkToFunctionHelper
  def link_to_function(name, *args, &block)
     html_options = args.extract_options!.symbolize_keys

     function = block_given? ? update_page(&block) : args[0] || ''
     onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
     href = html_options[:href] || '#'

     content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end
end

SurveyCreator/app/helpers/pages_helper.rb
module PagesHelper
end

SurveyCreator/app/helpers/results_helper.rb
module ResultsHelper
	def pageName
		"SurveyCreator"
	end
end

SurveyCreator/app/helpers/surveys_helper.rb
module SurveysHelper
end

SurveyCreator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Survey Creator!">
    <meta name="authors" content="Emmanuel, Miuyin y Ernesto">
    <title>Survey Creator</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:700' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
</head>
<body>
    <div id="wrapper">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
				<li class="col-md"><%= link_to "Home", root_path%></li>
				<li class="col-md"><%= link_to "Answer Surveys", published_surveys_path %></li> 
			<% if user_signed_in? %>
				<li class="col-md"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
				<li class="col-md"><%= link_to "Create Survey", new_survey_path%></li>
				<li class="col-md"><%=  link_to "Edit your unpublished surveys", surveys_path%></li>
			<%else%>
				<li class="col-md"><%= link_to "Log in", new_user_session_path%></li>
				<li class="col-md"><%= link_to "Create Account", new_user_registration_path%></li>
			<%end%>
            </ul>
        </div>
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="nav nav-pills">
                             <li role="presentation" class="active"><a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Menu</a></li>
                        </ul>
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
    
    </div>


    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

SurveyCreator/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

SurveyCreator/app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

SurveyCreator/app/views/pages/home.html.erb
<body id = "background"> 
	<h1>Welcome to Survey Creator!</h1>
</body>

SurveyCreator/app/views/responses/_form.html.erb
<%= form_for([@response.survey, @response]) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% for question in @survey.questions %>
      <label><%= question.question_content %></label>
      <%= select_tag :answer_content, options_for_select(["Very Good", "Good", "Average", "Bad", "Very Bad"]) %>
      <%= hidden_field_tag :question_id, question.id %>
    <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SurveyCreator/app/views/results/_form.html.erb
<% @counter = 0 %>
<%= form_for [@result.survey,@result] do |f| %>
  <%=f.hidden_field :survey_id, value: @result.survey.id %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.fields_for :answers do |answer| %>
      <label><%= @survey.questions[@counter].question_content %></label>
      <%= answer.hidden_field :question_id, value: @survey.questions[@counter].id %>
      <%= answer.select :answer_content, options_for_select(["Very Good", "Good", "Average", "Bad", "Very Bad"]) %>
      <% @counter = @counter + 1 %>
    <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SurveyCreator/app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results for <%= Survey.find_by_id(@results[0].survey_id).name %></h1>

<table>
  <thead>
    <tr>
      <th>Date Created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
      <td><%= result.created_at%>
      <td><%= link_to 'Show', survey_result_path(@survey,result) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', published_surveys_path %>

SurveyCreator/app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form' %>

<%= link_to 'Back', published_surveys_path %>

SurveyCreator/app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tbody>
    <tr>
      <td>Question</td>
      <td></td>
      <td>Answer</td>
      <td></td>
      <td></td>
    </tr> 

    <% @survey.questions.zip(@result.answers) do |ans, ans1| %>
    	<tr>
          <td><%= ans.question_content %></td> 
          <td></td>  
          <td><%= ans1.answer_content %></td>
      </tr>
    <% end %>

  </tbody>
</table>


<h1>You done! The <%= @survey.name %> Survey</h1>
<%= link_to 'Back', survey_results_path %>

SurveyCreator/app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', f: builder %>
  <% end %>
  <div class="field">
    <%= f.check_box :status%>
    <%= f.label :status, "Publish(only check this if you are sure 
    this is your final version of the survey)"%>
  </div>


  <p><%= link_to_add_fields "Add Question", f, :questions %></p>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SurveyCreator/app/views/surveys/_question_fields.html.erb
<div class="field">
  <%= f.label :question_content, "Question" %>
  <%= f.text_area :question_content, :rows => 3 %>
  <%= f.check_box :_destroy%>
  <%= f.label :_destroy, "Remove question"%>
<div/>

SurveyCreator/app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

SurveyCreator/app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
      <% if current_user.id == User.find_by_id(survey.user_id).id && survey.status == false%>
          <td><%= survey.name %></td>
          <td><%= link_to 'Show', survey %></td>
          <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

SurveyCreator/app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

SurveyCreator/app/views/surveys/published.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Public Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Survey Name</th>
      <th>Created By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= User.find_by_id(survey.user_id).email %>
        <td><%= link_to "Look the Answers", survey_results_path(survey) %></td>
        <td><%= link_to "Answer Survey", new_survey_result_path(survey) %></td>
        </tr>
    <% end %>
  </tbody>
</table>

SurveyCreator/app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @survey.name %>
</p>

<p>

<ol>
	<% for question in @survey.questions %>
		<li><%= question.question_content %></li>
	<% end %>
</ol>
<% if @survey.status == false %>
	<%= link_to 'Edit', edit_survey_path(@survey) %> 
<% end %>
<%= link_to 'Back', surveys_path %>